// CONSTANTS LOGIN
export const SIGNIN_REQUESTED = "SIGNIN_REQUESTED";
export const SIGNIN_SUCCEEDED = "SIGNIN_SUCCEEDED";
export const SIGNIN_FAILED = "SIGNIN_FAILED";

// NOTIFICATION
export const NOTIFICATION_REQUESTED = "NOTIFICATION_REQUESTED";
